{% set name = "cabinetry" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a111fb3eb0a979555d39fda28ecc358ace6a4a052d31c52df9880d060c9a722c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cabinetry = cabinetry.cli:cabinetry

requirements:
  build:
    - setuptools >=42
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyhf ~=0.7.0
    - iminuit >=2.7.0
    - boost-histogram >=1.0.0
    - tabulate >=0.8.1
    - matplotlib-base >=3.5.0

test:
  imports:
    - cabinetry
  commands:
    - pip check
    - cabinetry --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/cabinetry
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: library for building and steering binned template fits

  description: |
    cabinetry is a Python library for building and steering binned template fits.
    It is written with applications in High Energy Physics in mind.
    cabinetry interfaces many other powerful libraries to make it easy for an analyzer to run their statistical inference pipeline.
    Statistical models in HistFactory format can be built by cabinetry from instructions in a declarative configuration.
    cabinetry makes heavy use of pyhf for statistical inference, and provides additional utilities to help study and disseminate fit results.
    This includes commonly used visualizations. Due to its modular approach, analyzers are free to use all of cabinetry's functionality or only some pieces.
    cabinetry can be used for inference and visualization with any pyhf-compatible model, whether it was built with cabinetry or not.
  doc_url: https://cabinetry.readthedocs.io/en/latest/
  dev_url: https://github.com/scikit-hep/cabinetry

extra:
  recipe-maintainers:
    - alexander-held
    - matthewfeickert
    - conda-forge/scikit-hep
